# Vectorized Distance Metrics


In [197]:
# Create Some Basic Testing Data
import numpy as np

train_data = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10]])
test_data = np.array([[5, 10, 15], [10, 20, 30]])

print("Train Data: \n" + str(train_data))
print("Test Data: \n" + str(test_data))

Train Data: 
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
Test Data: 
[[ 5 10 15]
 [10 20 30]]


## Euclidean

In [245]:
# Find Difference Between Train and Test Vectors
diff = train_data-test_data[:, np.newaxis]
print("Difference Of Vectors: \n" + str(diff))

Difference Of Vectors: 
[[[ -4  -8 -12]
  [  0  -4  -8]
  [  3  -1  -5]]

 [[ -9 -18 -27]
  [ -5 -14 -23]
  [ -2 -11 -20]]]


In [246]:
squares = np.square(diff)
print("Square Of Differences: \n" + str(squares))

Square Of Differences: 
[[[ 16  64 144]
  [  0  16  64]
  [  9   1  25]]

 [[ 81 324 729]
  [ 25 196 529]
  [  4 121 400]]]


In [247]:
sum_of_squares = np.sum(np.square(test), axis=2)
print("Sum Of Squares: \n" + str(sum_of_squares))

Sum Of Squares: 
[[ 224   80   35]
 [1134  750  525]]


In [248]:
distance_matrix = np.sqrt(np.sum(np.square(test), axis=2))
print("Distance Matrix:\n" + str(distance_matrix))

Distance Matrix:
[[14.96662955  8.94427191  5.91607978]
 [33.67491648 27.38612788 22.91287847]]


In [258]:
from knn.distance_metrics import euclidean

rand_train = np.random.randn(100,10)
rand_test = np.random.randn(100,10)

def euclidean_vect(train_data, test_data):
    return np.sqrt(np.sum(np.square(train_data-test_data[:, np.newaxis]), axis=2))

def euclidean_no_vect(train_data, test_data):
    distance_matrix = np.zeros((test_data.shape[0], train_data.shape[0]))
    for col, train_vect in enumerate(train_data):
        for row, test_vect in enumerate(test_data):
            distance_matrix[row, col] = euclidean(train_vect, test_vect)
    return distance_matrix


print("Vectorized Result: \n" + str(euclidean_vect(train_data, test_data)))
print("Non-Vectorized Result: \n" + str(euclidean_no_vect(train_data, test_data)))

print("Vectorized Timing:")
%time result = euclidean_vect(rand_train, rand_test)
print("Non-Vectorized Timing:")
%time result = euclidean_no_vect(rand_train, rand_test)

Vectorized Result: 
[[14.96662955  8.94427191  5.91607978]
 [33.67491648 27.38612788 22.91287847]]
Non-Vectorized Result: 
[[14.96662955  8.94427191  5.91607978]
 [33.67491648 27.38612788 22.91287847]]
Vectorized Timing:
CPU times: user 1.02 ms, sys: 353 µs, total: 1.38 ms
Wall time: 904 µs
Non-Vectorized Timing:
CPU times: user 39.2 ms, sys: 1.63 ms, total: 40.8 ms
Wall time: 40 ms


## L1-Norm or Manhattan Distance

In [268]:
# Find Difference Between Train and Test Vectors
diff = train_data-test_data[:, np.newaxis]
print("Difference Of Vectors: \n" + str(diff))

Difference Of Vectors: 
[[[ -4  -8 -12]
  [  0  -4  -8]
  [  3  -1  -5]]

 [[ -9 -18 -27]
  [ -5 -14 -23]
  [ -2 -11 -20]]]


In [269]:
absolute_diff = np.abs(diff)
print("Absolute Differences: \n" + str(absolute_diff))

Absolute Differences: 
[[[ 4  8 12]
  [ 0  4  8]
  [ 3  1  5]]

 [[ 9 18 27]
  [ 5 14 23]
  [ 2 11 20]]]


In [270]:
distance_matrix = np.sum(absolute_diff, axis=2)
print("Distance Matrix:\n" + str(distance_matrix))

Distance Matrix:
[[24 12  9]
 [54 42 33]]


In [274]:
from knn.distance_metrics import manhattan

rand_train = np.random.randn(100,10)
rand_test = np.random.randn(100,10)

def manhattan_vect(train_data, test_data):
    return np.sum(np.abs(train_data-test_data[:, np.newaxis]), axis=2)

def manhattan_no_vect(train_data, test_data):
    distance_matrix = np.zeros((test_data.shape[0], train_data.shape[0]))
    for col, train_vect in enumerate(train_data):
        for row, test_vect in enumerate(test_data):
            distance_matrix[row, col] = manhattan(train_vect, test_vect)
    return distance_matrix


print("Vectorized Result: \n" + str(manhattan_vect(train_data, test_data)))
print("Non-Vectorized Result: \n" + str(manhattan_no_vect(train_data, test_data)))

print("Vectorized Timing:")
%time result = euclidean_vect(rand_train, rand_test)
print("Non-Vectorized Timing:")
%time result = euclidean_no_vect(rand_train, rand_test)

Vectorized Result: 
[[24 12  9]
 [54 42 33]]
Non-Vectorized Result: 
[[24. 12.  9.]
 [54. 42. 33.]]
Vectorized Timing:
CPU times: user 1.23 ms, sys: 294 µs, total: 1.52 ms
Wall time: 866 µs
Non-Vectorized Timing:
CPU times: user 40.8 ms, sys: 1.12 ms, total: 41.9 ms
Wall time: 41.2 ms


## Hamming Distance

In [279]:
differences = train_data != test_data[:, np.newaxis]
print("Logical Differences: \n" + str(differences))

[[[ True  True  True]
  [False  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [281]:
sum_of_diffs = np.sum(np.abs(train_data != test_data[:, np.newaxis]), axis=2)
print("Sum Of Differences: \n" + str(sum_of_diffs))

Sum Of Differences: 
[[3 2 3]
 [3 3 3]]


In [284]:
from knn.distance_metrics import hamming

rand_train = np.random.randn(100,10)
rand_test = np.random.randn(100,10)

def hamming_vect(train_data, test_data):
    return np.sum(np.abs(train_data != test_data[:, np.newaxis]), axis=2)

def hamming_no_vect(train_data, test_data):
    distance_matrix = np.zeros((test_data.shape[0], train_data.shape[0]))
    for col, train_vect in enumerate(train_data):
        for row, test_vect in enumerate(test_data):
            distance_matrix[row, col] = hamming(train_vect, test_vect)
    return distance_matrix


print("Vectorized Result: \n" + str(hamming_vect(train_data, test_data)))
print("Non-Vectorized Result: \n" + str(hamming_no_vect(train_data, test_data)))

print("Vectorized Timing:")
%time result = hamming_vect(rand_train, rand_test)
print("Non-Vectorized Timing:")
%time result = hamming_no_vect(rand_train, rand_test)

Vectorized Result: 
[[3 2 3]
 [3 3 3]]
Non-Vectorized Result: 
[[3. 2. 3.]
 [3. 3. 3.]]
Vectorized Timing:
CPU times: user 1.83 ms, sys: 1.1 ms, total: 2.93 ms
Wall time: 1.51 ms
Non-Vectorized Timing:
CPU times: user 70.8 ms, sys: 745 µs, total: 71.5 ms
Wall time: 72.7 ms


## Cosine Sim

In [290]:
train_norms = np.sum(np.square(train_data), axis=1)
test_norms = np.sum(np.square(test_data), axis=1)
print("Train Vector Norms:\n" + str(train_norms))
print("Test Vector Norms:\n" + str(test_norms))

Train Vector Norms:
[ 14 110 245]
Test Vector Norms:
[ 350 1400]


In [292]:
prod_of_norms = np.outer(train_norms, test_norms)
print("Product Of Norms:\n" + str(prod_of_norms))

Product Of Norms:
[[  4900  19600]
 [ 38500 154000]
 [ 85750 343000]]


In [293]:
dots = np.dot(train_data, test_data.T)
print("Dot Products:\n" + str(dots))

Dot Products:
[[ 70 140]
 [190 380]
 [280 560]]


In [294]:
similarity_matrix = dots/norm_prods
print("Similarity Matrix:\n" + str(similarity_matrix))

Similarity Matrix:
[[0.01428571 0.00714286]
 [0.00493506 0.00246753]
 [0.00326531 0.00163265]]


In [312]:
from knn.distance_metrics import cosine

def cosine_vect(train_data, test_data):
    train_norms = np.sqrt(np.sum(np.square(train_data), axis=1))
    test_norms = np.sqrt(np.sum(np.square(test_data), axis=1))
    return 1-(np.dot(train_data, test_data.T)/np.outer(train_norms, test_norms)).T

def cosine_no_vect(train_data, test_data):
    distance_matrix = np.zeros((test_data.shape[0], train_data.shape[0]))
    for col, train_vect in enumerate(train_data):
        for row, test_vect in enumerate(test_data):
            distance_matrix[row, col] = cosine(train_vect, test_vect)
    return distance_matrix
            
            
print("Vectorized Result: \n" + str(cosine_vect(train_data, test_data)))
print("Non-Vectorized Result: \n" + str(cosine_no_vect(train_data, test_data)))

print("Vectorized Timing:")
%time result = cosine_vect(rand_train, rand_test)
print("Non-Vectorized Timing:")
%time result = cosine_no_vect(rand_train, rand_test)

Vectorized Result: 
[[0.         0.03167034 0.04381711]
 [0.         0.03167034 0.04381711]]
Non-Vectorized Result: 
[[0.         0.03167034 0.04381711]
 [0.         0.03167034 0.04381711]]
Vectorized Timing:
CPU times: user 713 µs, sys: 323 µs, total: 1.04 ms
Wall time: 727 µs
Non-Vectorized Timing:
CPU times: user 81 ms, sys: 1.31 ms, total: 82.3 ms
Wall time: 82.6 ms


# Correlation

In [298]:
mean_removed_train = train_data-np.mean(train_data, axis=1)[:, np.newaxis]
mean_removed_test = test_data-np.mean(test_data, axis=1)[:, np.newaxis,]

print("Mean Removed Train:\n" + str(mean_removed_train))
print("Mean Removed Test:\n" + str(mean_removed_test))

Mean Removed Train:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
Mean Removed Test:
[[ -5.   0.   5.]
 [-10.   0.  10.]]


In [304]:
std_dev_train = np.sqrt(np.sum(np.square(mean_removed_train), axis=1))
print("Std Dev Train:\n" + str(std_dev_a))

std_dev_test = np.sqrt(np.sum(np.square(mean_removed_test), axis=1))
print("Std Dev Train:\n" + str(std_dev_b))

Std Dev Train:
[1.41421356 1.41421356 1.41421356]
Std Dev Train:
[ 7.07106781 14.14213562]


In [305]:
cov = np.dot(mean_removed_train, mean_removed_test.T)
print("Covariance Matrix:\n" + str(cov))

Covariance Matrix:
[[10. 20.]
 [10. 20.]
 [10. 20.]]


In [307]:
std_dev_dot = np.outer(std_dev_train, std_dev_test)
print("Std Dev Dots:\n" + str(std_dev_dot))

Std Dev Dots:
[[10. 20.]
 [10. 20.]
 [10. 20.]]


In [308]:
correlations = cov/std_dev_dot
print("Correlations:\n" + str(correlations))

Correlations:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [314]:
from knn.distance_metrics import pearson

def pearson_vect(train_data, test_data):
    mean_removed_train = (train_data-np.mean(train_data, axis=1)[:, np.newaxis])
    mean_removed_test = (test_data-np.mean(test_data, axis=1)[:, np.newaxis])
    std_dev_train = np.sqrt(np.sum(np.square(mean_removed_train), axis=1))
    std_dev_test = np.sqrt(np.sum(np.square(mean_removed_test), axis=1))
    return 1-np.dot(mean_removed_train, mean_removed_test.T)/np.outer(std_dev_train, std_dev_test)

def pearson_no_vect(train_data, test_data):
    distance_matrix = np.zeros((test_data.shape[0], train_data.shape[0]))
    for col, train_vect in enumerate(train_data):
        for row, test_vect in enumerate(test_data):
            distance_matrix[row, col] = pearson(train_vect, test_vect)
    return distance_matrix



print("Vectorized Result: \n" + str(pearson_vect(train_data, test_data)))
print("Non-Vectorized Result: \n" + str(pearson_no_vect(train_data, test_data)))

print("Vectorized Timing:")
%time result = pearson_vect(rand_train, rand_test)
print("Non-Vectorized Timing:")
%time result = pearson_no_vect(rand_train, rand_test)

Vectorized Result: 
[[2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 2.22044605e-16]]
Non-Vectorized Result: 
[[2.22044605e-16 2.22044605e-16 2.22044605e-16]
 [2.22044605e-16 2.22044605e-16 2.22044605e-16]]
Vectorized Timing:
CPU times: user 396 µs, sys: 222 µs, total: 618 µs
Wall time: 405 µs
Non-Vectorized Timing:
CPU times: user 322 ms, sys: 10.5 ms, total: 332 ms
Wall time: 328 ms


## Benchmarking With KNN

In [369]:
rand_train = np.random.randn(5000,10)
rand_test = np.random.randn(500,10)

In [374]:
def knn_bf_introselect(train, test , distance, k=1):
    distance_matrix = distance(train, test)
    k_smallest_ind = np.argpartition(distance_matrix, k-1)[:,:k]
    
    smallest_k_matrix = np.zeros((test.shape[0], k), dtype=[("index",int), ("dist",float)])
    for i, ind_set in enumerate(k_smallest_ind):
        for j, element in enumerate(ind_set):
            smallest_k_matrix[i, j] = (element, distance_matrix[i, element])
    
    return smallest_k_matrix
    

print("KNN - Introselect k=1: \n" + str(knn_bf_introselect(train_data, test_data, euclidean_vect , 2)))

%timeit -r 15 result_1 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 1);
%timeit -r 15 result_2 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 3);
%timeit -r 15 result_3 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 5);
%timeit -r 15 result_4 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 7);

KNN - Introselect k=1: 
[[(2,  5.91607978) (1,  8.94427191)]
 [(2, 22.91287847) (1, 27.38612788)]]
49.6 ms ± 2.88 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
56.2 ms ± 4.29 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
75.9 ms ± 2.17 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
80.2 ms ± 1.02 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)


In [373]:
import heapq

def knn_bf_max_heap(train, test, distance, k=1):
    distance_matrix = distance(train, test)
    
    smallest_k_matrix = np.zeros((test.shape[0], k), dtype=[("index",int), ("dist",float)])
    for index, row in enumerate(distance_matrix):
        heapq.heapify(row.tolist())
        smallest_k_matrix[index,:] = heapq.nsmallest(k, enumerate(row), key=lambda x: x[1])
        
    return smallest_k_matrix
    
    
print("KNN - Introselect k=1: \n" + str(knn_bf_max_heap(train_data, test_data, euclidean_vect , 2)))
%timeit -r 15 result_1 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 1);
%timeit -r 15 result_2 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 3);
%timeit -r 15 result_3 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 5);
%timeit -r 15 result_4 = knn_bf_introselect(rand_train, rand_test, cosine_vect, 7);

KNN - Introselect k=1: 
[[(2,  5.91607978) (1,  8.94427191)]
 [(2, 22.91287847) (1, 27.38612788)]]
63.3 ms ± 5.68 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
60.2 ms ± 6.62 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
77.1 ms ± 1.27 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
80.1 ms ± 1.29 ms per loop (mean ± std. dev. of 15 runs, 10 loops each)
